void (*applybounds)(Client *c, struct wlr_box *bbox);
void (*applyrules)(Client *c);
void (*arrange)(Monitor *m);
void (*arrangelayer)(Monitor *m, struct wl_list *list,
		struct wlr_box *usable_area, int exclusive);
void (*arrangelayers)(Monitor *m);
void (*axisnotify)(struct wl_listener *listener, void *data);
void (*buttonpress)(struct wl_listener *listener, void *data);
void (*chvt)(const Arg *arg);
void (*checkidleinhibitor)(struct wlr_surface *exclude);
void (*cleanup)(void);
void (*cleanupmon)(struct wl_listener *listener, void *data);
void (*closemon)(Monitor *m);
void (*commitlayersurfacenotify)(struct wl_listener *listener, void *data);
void (*commitnotify)(struct wl_listener *listener, void *data);
void (*commitpopup)(struct wl_listener *listener, void *data);
void (*createdecoration)(struct wl_listener *listener, void *data);
void (*createidleinhibitor)(struct wl_listener *listener, void *data);
void (*createkeyboard)(struct wlr_keyboard *keyboard);
KeyboardGroup *(*createkeyboardgroup)(void);
void (*createlayersurface)(struct wl_listener *listener, void *data);
void (*createlocksurface)(struct wl_listener *listener, void *data);
void (*createmon)(struct wl_listener *listener, void *data);
void (*createnotify)(struct wl_listener *listener, void *data);
void (*createpointer)(struct wlr_pointer *pointer);
void (*createpointerconstraint)(struct wl_listener *listener, void *data);
void (*createpopup)(struct wl_listener *listener, void *data);
void (*cursorconstrain)(struct wlr_pointer_constraint_v1 *constraint);
void (*cursorframe)(struct wl_listener *listener, void *data);
void (*cursorwarptohint)(void);
void (*destroydecoration)(struct wl_listener *listener, void *data);
void (*destroydragicon)(struct wl_listener *listener, void *data);
void (*destroyidleinhibitor)(struct wl_listener *listener, void *data);
void (*destroylayersurfacenotify)(struct wl_listener *listener, void *data);
void (*destroylock)(SessionLock *lock, int unlocked);
void (*destroylocksurface)(struct wl_listener *listener, void *data);
void (*destroynotify)(struct wl_listener *listener, void *data);
void (*destroypointerconstraint)(struct wl_listener *listener, void *data);
void (*destroysessionlock)(struct wl_listener *listener, void *data);
void (*destroysessionmgr)(struct wl_listener *listener, void *data);
void (*destroykeyboardgroup)(struct wl_listener *listener, void *data);
Monitor *(*dirtomon)(enum wlr_direction dir);
void (*focusclient)(Client *c, int lift);
void (*focusmon)(const Arg *arg);
void (*focusstack)(const Arg *arg);
Client *(*focustop)(Monitor *m);
void (*fullscreennotify)(struct wl_listener *listener, void *data);
void (*gpureset)(struct wl_listener *listener, void *data);
void (*handlesig)(int signo);
void (*incnmaster)(const Arg *arg);
void (*inputdevice)(struct wl_listener *listener, void *data);
int *(keybinding)(uint32_t mods, xkb_keysym_t sym);
void (*keypress)(struct wl_listener *listener, void *data);
void (*keypressmod)(struct wl_listener *listener, void *data);
int *(keyrepeat)(void *data);
void (*killclient)(const Arg *arg);
void (*locksession)(struct wl_listener *listener, void *data);
void (*mapnotify)(struct wl_listener *listener, void *data);
void (*maximizenotify)(struct wl_listener *listener, void *data);
void (*monocle)(Monitor *m);
void (*motionabsolute)(struct wl_listener *listener, void *data);
void (*motionnotify)(uint32_t time, struct wlr_input_device *device, double sx,
		double sy, double sx_unaccel, double sy_unaccel);
void (*motionrelative)(struct wl_listener *listener, void *data);
void (*moveresize)(const Arg *arg);
void (*outputmgrapply)(struct wl_listener *listener, void *data);
void (*outputmgrapplyortest)(struct wlr_output_configuration_v1 *config, int test);
void (*outputmgrtest)(struct wl_listener *listener, void *data);
void (*pointerfocus)(Client *c, struct wlr_surface *surface,
		double sx, double sy, uint32_t time);
void (*printstatus)(void);
void (*powermgrsetmode)(struct wl_listener *listener, void *data);
void (*quit)(const Arg *arg);
void (*rendermon)(struct wl_listener *listener, void *data);
void (*requestdecorationmode)(struct wl_listener *listener, void *data);
void (*requeststartdrag)(struct wl_listener *listener, void *data);
void (*requestmonstate)(struct wl_listener *listener, void *data);
void (*resize)(Client *c, struct wlr_box geo, int interact);
void (*run)(char *startup_cmd);
void (*setcursor)(struct wl_listener *listener, void *data);
void (*setcursorshape)(struct wl_listener *listener, void *data);
void (*setfloating)(Client *c, int floating);
void (*setfullscreen)(Client *c, int fullscreen);
void (*setgamma)(struct wl_listener *listener, void *data);
void (*setlayout)(const Arg *arg);
void (*setmfact)(const Arg *arg);
void (*setmon)(Client *c, Monitor *m, uint32_t newtags);
void (*setpsel)(struct wl_listener *listener, void *data);
void (*setsel)(struct wl_listener *listener, void *data);
void (*setup)(void);
void (*spawn)(const Arg *arg);
void (*startdrag)(struct wl_listener *listener, void *data);
void (*tag)(const Arg *arg);
void (*tagmon)(const Arg *arg);
void (*tile)(Monitor *m);
void (*togglefloating)(const Arg *arg);
void (*togglefullscreen)(const Arg *arg);
void (*toggletag)(const Arg *arg);
void (*toggleview)(const Arg *arg);
void (*unlocksession)(struct wl_listener *listener, void *data);
void (*unmaplayersurfacenotify)(struct wl_listener *listener, void *data);
void (*unmapnotify)(struct wl_listener *listener, void *data);
void (*updatemons)(struct wl_listener *listener, void *data);
void (*updatetitle)(struct wl_listener *listener, void *data);
void (*urgent)(struct wl_listener *listener, void *data);
void (*view)(const Arg *arg);
void (*viewtag)(const Arg *arg);
void (*virtualkeyboard)(struct wl_listener *listener, void *data);
void (*virtualpointer)(struct wl_listener *listener, void *data);
Monitor *(*xytomon)(double x, double y);
void (*xytonode)(double x, double y, struct wlr_surface **psurface,
		Client **pc, LayerSurface **pl, double *nx, double *ny);
void (*zoom)(const Arg *arg);
